#!/bin/bash


function checking ()
{
for x in "${@:2}";
do [[ "$x" == "$1" ]] && return 0;
done
return 1
}

mkdir $2
cd $2 # $2-directory to store pages

queue=( $1 ) #page


for((i=0; i<$3; i++))  # $3-max depth level

do

for((j=0; j <${#queue[@]}; j++))

do

if checking "${queue[j]}" "${checkedurl[@]}"

then

continue 

fi

curl -s "${queue[j]}" > /dev/null   > "strona[$j]"

tempqueue=( $(grep -Eo 'href="([^"#]+)' $( ls -t | head -1 ) | cut -d'"' -f2)) #temporary array

tempqueue=( "${tempqueue[@]/#'/'/"${queue[j]}/"}" ) #changing relative links to absolute
beforequeue=( "${beforequue[@]}" "${tempqueue[@]}" ) 

done 

checkedurl=( "${checkedurl[@]}" "${queue[@]}" ) #list of all urls
queue=( "${beforequeue[@]}" )

done


