#!/bin/bash

traverse (){

local depth=$1

shift

for x in "$@"; do

#while  read -r line
 #do

# curl $line >> page3
echo "directory contains: $@"
#echo "name - $line"
#IFS=$'\r\n' GLOBIGNORE="*"  command eval  'myARR=($(cat page2))'
#echo "${myARR[@]}"
#done < 
temp=()
#grep -i -E '<a href=".*">' page3 > page4
#grep -E -o 'href="([^"#]+)' page4 | cut -d'"' -f2 > page5 
#grep http page5 > page2

for y in "$x"/*; do
echo "$x/$y"
temp+=( "$x/$y" )

done
done
 ((--depth))

if((depth>0)); then 

traverse $depth "${temp[@]}"

fi

}

dir=( a b c d )
init_depth=3 
traverse  $init_depth "${dir[@]}"

