#!/bin/bash

address="https://blog.garage-coding.com"

curl $address > page
grep -i -E '<a href=".*">' page > page1
grep -E -o 'href="([^"#]+)' page1 | cut -d'"' -f2 > page2
cat page2
myArr=()
myArr+=($address) 





IFS=$'\r\n' GLOBIGNORE="*"  command eval  'myArr=($(cat page2))'
echo "${myArr[@]}"
